name: Generate Keystore

on:
  # 允許我們手動觸發這個 workflow
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and Encode Keystore
        run: |
          # --- 您可以在這裡修改密碼和別名，但使用預設值最簡單 ---
          KEY_PASSWORD="android"
          KEYSTORE_PASSWORD="android"
          ALIAS="upload"
          # --- 以下為 keytool 指令 ---
          keytool -genkeypair -v \
            -keystore upload-keystore.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias $ALIAS \
            -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD

          # --- 將產生的檔案編碼成 Base64 並印出來 ---
          echo "--- COPY THE STRING BELOW TO THE KEYSTORE_BASE64 SECRET ---"
          base64 --wrap=0 upload-keystore.jks
          echo "-----------------------------------------------------------"
          echo " "
          echo "--- USE THESE VALUES FOR THE OTHER SECRETS ---"
          echo "KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD"
          echo "KEY_ALIAS: $ALIAS"
          echo "KEY_PASSWORD: $KEY_PASSWORD"
          echo "------------------------------------------------"
